# Generated by Django 4.2.1 on 2023-05-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='total',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total',
            name='sum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.history'),
        ),
    ]
